### ISSUE TITLE
Secondary audio track rarely works

### ISSUE THREAD

**Issue by aimtrainer** [brusiks/multi-language-video-player#3]
I tried multi-language-video-player yesterday to watch a movie with my girlfriend, so that she could listen to the german and I to the english audio track, one over HDMI audio (tv's speakers), the other over bluetooth headphones.
Unfortunately it rarely actually played the english / the secondary audio track. When I selected english for both tv and headphones, and restarted the program a few times it eventually played english over HDMI.
This got annoying when after about 15 minutes I got some error message (something about hdmi, not enough time to read) followed by a black screen for a few seconds. Then the playback resumed but without the tv's audio. I had to restart the program, just to have the same problem again after another 15 minutes.

I ended up playing the movie on my phone with headphones and syncing it manually to the tv.

I've been looking all over the web for a simple solution to watch a movie with two different audio tracks simultaneously. I would really love this tool to work flawlessly for me.

I'm using vlc 3.0.8 btw.

Thanks for sharing your work!

**Comment by brusiks** [comment]
Hi, thank you for the feedback. 

Sorry to hear that. I'm not using it for a long time and I've never tested it on different environments.

I tried to fix it. Tested it on my laptop with headphones. You can try it out https://github.com/brusiks/multi-language-video-player/releases

There still an issue with audio sync, don't have time to find a way to improve on that. But it can easily be eliminated by this workaround from Readme:
You can see the fact of out sync on the video duration indicator. The number in parentheses indicates how large out of sync is in seconds. When the time indicator turns red it means that audio is out of sync. To eliminate out of sync you can seek to the current time by clicking on it on a seek bar. Do it multiple times until there will be no out of sync.

I really hope that it will work for you. I understand how it is annoying that there is no such normal video player for that purpose, that's why I did this primitive app.
